export default function TermsofUse() {
  return (
    <div className="bg-gray-900 px-6 py-32 lg:px-8">
      <div className="mx-auto max-w-3xl text-base leading-7 text-white">
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">Terms of Use</h1>
        <p className="mt-6 text-xl leading-8">
          



        USER AGREEMENT

Computerscience.careers is a service of Rupe Enterprises LLC (hereafter referred to as COMPANY).  Please read this User Agreement before using
Computerscience.careers (hereafter referred to as SITE) and our service.  

Our Service is provided to you for your personal, non-commercial enjoyment.  In continuing to use our Service you are agreeing to abide by certain terms and conditions as follows:

We May Modify the Terms of This User Agreement From Time to Time: We reserve the right to change the terms of this User Agreement or to modify any features of our Service at any time without notice to you and, by continuing to use our Service, you agree to be bound by such changes.  Any changes to this User Agreement shall become a part of this User Agreement and shall apply as soon as they are posted.  The most current version of the User Agreement can be viewed at any time at:
Computerscience.careers .  Unless explicitly stated otherwise, any new features or functionality that augment or enhance our Service shall be subject to this User Agreement.

We May Terminate the Service or Your Use of the Service: We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, our Service (or any part thereof) with or without notice. You agree that we shall not be liable to you or any third party for any modification, suspension or discontinuance of our Service.  Further, we may, in our sole discretion, terminate or suspend your access to and use of our Service (or any part thereof) at any time for any reason (including, without limitation, if we believe that you have violated or acted inconsistently with the terms of the following paragraph) or no reason whatsoever.

In Using Our Service You Agree to Comply with Certain Basic Rules: To the extent required you agree to provide true, accurate, current and complete information about yourself as prompted by any subscription form and/or any registration form.  If any information provided by you is untrue, inaccurate, not current or incomplete, we reserve the right to terminate your subscription and refuse any and all current or future use of our Service in our sole discretion.  When you register with us, you accept responsibility for all activities that occur under your account or password and you agree you will not sell, transfer or assign your membership or any membership rights.

As part of your subscription, you agree to not use our Service to:

    upload, post, publish, email, reproduce, distribute or otherwise transmit any information, data, text, music, sound, photographs, graphics, video, messages or other materials that are unlawful, harmful, threatening, embarrassing, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, deceptive, fraudulent, contain explicit or graphic descriptions or accounts of sexual acts, invasive of another’s privacy, or hateful;
    “stalk” another;
    upload, post, publish, email, reproduce, distribute or otherwise transmit any content that victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;
    harm minors in any way;
    impersonate any person or entity, including, but not limited to, a COMPANY officer or another employee, or falsely state or otherwise misrepresent your affiliation with a person or entity;
    forge headers or otherwise manipulate identifiers in order to disguise the origin of any content transmitted to or through our Service;
    upload, post, publish, email, reproduce, distribute or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, “junk mail,” “Spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation;
    upload, post, publish, email, reproduce, distribute or otherwise transmit any material that contains software viruses, Trojan horses, worms, time bombs, cancelbots, or any other computer code, files or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment or any other similarly destructive activity, or surreptitiously intercept or expropriate any system, data or personal information;
    act in a manner that negatively affects other users’ ability to use our Service;
    interfere with or disrupt our Service or servers or networks connected to our Service, or disobey any requirements, procedures, policies or regulations of networks connected to our Service; or
    intentionally or unintentionally violate any applicable local, state, national or international law.

You also agree that you will not harvest, collect or store information about the users of our Service or the content posted by others on our Service or use such information for any purpose inconsistent with the purpose of our Service or for the purpose of transmitting or facilitating transmission of unsolicited bulk electronic mail or communications.

Our Users May Submit Content to Our Service (Including Comments):  You acknowledge that we are not responsible for material submitted to SITE by users.  For purposes of this User Agreement, references herein to content or materials submitted by a user include without limitation any reader comments such user may make on or otherwise add to our Service.  We may not pre-screen, monitor, review or edit the content posted by users.  However, we have the right (but not the obligation) in our sole discretion to refuse or remove any content, in whole or part, that, in our judgment, does not comply with this User Agreement or is otherwise undesirable, inappropriate or inaccurate.  We are not responsible for any failure, non-failure or delay in removing such content.  Users will remain responsible for the accuracy, copyright compliance, legality, decency, or any other aspect of any content they submit.  Under no circumstances will we be liable in any way for any content a user submits, including, but not limited to, any errors or omissions in any such content, or any loss or damage of any kind incurred as a result of your use of any such content.  You agree to immediately notify us of any unauthorized use of our Service or any other breach of security known or suspected by you.

You acknowledge and agree that COMPANY may preserve content and may also disclose content if required to do so by law or in the good-faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce this User Agreement; (c) respond to claims that any content violates the rights of third-parties; or (d) protect the rights, property, or personal safety of SITE, its users or the public.

We assume no responsibility for the deletion, alteration or failure to store postings, content or other information submitted by you or other users to our Service.

You represent and warrant that (i) any content you submit is either original to you, or all third party rights have been fully cleared for use; and (ii) such content does not and will not, in any way, violate or breach any of the terms of this User Agreement.  In furtherance of the foregoing, you agree that you will not: (A) submit content that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant us all of the rights granted herein; (B) publish falsehoods or misrepresentations that could damage us or any third party; (C) submit content that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; or (D) post advertisements or solicitations of business.  You understand that when you submit content in any form to SITE we may authorize such content to be distributed or syndicated to or published on our other affiliated sites.

In operating our Service, we do not solicit nor do we wish to receive any confidential, secret or proprietary information or other material from you through our Service or in any other way. Any information or material submitted or sent to us will be deemed not to be confidential or secret. Without limiting the generality of any other terms of this User Agreement, by submitting or sending information or other material to us, you represent and warrant that the information is original to you and that no other party has any rights to the material.

In submitting any content to our Service please follow codes of social decency.  Be respectful of others’ opinions and comments so we can continue to build a community for everyone to enjoy. Personal attacks and all other forms of harassment are prohibited.

Finally, by submitting content to our Service, a user is giving us a world-wide, perpetual, irrevocable, non-exclusive and fully sub-licensable right and license to use for any purpose, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such content (in whole or part), including any information, suggestions, ideas, drawings or concepts contained in such content, worldwide and/or to incorporate it in other works in any form, media, or technology now known or later developed.  You warrant that any “moral rights” in any such materials have been waived.  We shall not in any circumstance be required to pay or incur any sums to any person or entity as a result of our use or exploitation of content submitted by you.  Without limiting the foregoing clause, we may publicly display advertisements and other information adjacent to or included with your content.   You are not entitled to any compensation relating to such advertisements. The manner, mode and extent of such advertising are subject to change without specific notice to you.

From Time to Time We May Run Various Promotions:  Our Service may contain or offer sweepstakes or other promotions, which may be governed by a separate set of rules that describe the sweepstakes or promotion and may have eligibility requirements, such as certain age or geographic area restrictions. It is your responsibility to read those rules to determine whether or not your participation, registration or entry will be valid and to determine the sponsor’s requirements of you in connection with the applicable sweepstakes or promotion.

We are an Internet Service Provider, e.g., We are Not Responsible For and Do Not Necessarily Hold the Opinions Expressed by Our Content Contributors: Opinions and other statements expressed by users and third parties are theirs alone, not opinions of COMPANY.  Content created by third parties is the sole responsibility of the third parties and its accuracy and completeness are not endorsed or guaranteed.  You acknowledge that by providing you with the ability to view and potentially distribute content through our Service, we are not undertaking any obligation or liability relating to the content.  We do not undertake or assume any duty to monitor our Service for inappropriate or unlawful content.  We assume no responsibility or liability which may arise from the content thereof, including, but not limited to, claims for defamation, libel, slander, infringement, invasion of privacy and publicity rights, obscenity, pornography, profanity, fraud, or misrepresentation. Notwithstanding the foregoing, we reserve the right to block or remove communications, postings or materials at any time in our sole discretion.

We May Allow You to Engage in Certain Personal uses of our Service That Include the Ability to Share Content:  For example, we may allow you to post our content on a social networking site by pasting the applicable HTML or other code provided by us (typically labeled as an embed code) (“Widgets”).  We may discontinue providing the services necessary for the Widgets to operate or we may disable Widgets you have embedded at any time for any reason without any liability to you.  You agree that our permission to you to use Widgets on any such site does not provide you (or any third party) with any intellectual property rights in or to the Widget or any portion of our Service made available via any Widget.

You agree that you will not embed or otherwise make available a Widget on a web page or web site containing content that is threatening, abusive, harassing, hateful, or racially, ethnically or otherwise objectionable (in our opinion).  We make no specific warranties about Widgets.  You agree not to circumvent (or in any way attempt to circumvent) the security or rights management features in the Widget or any component of the Widget (including any video player) that are designed to prevent users from copying, manipulating or retaining the content made available via the Widget.  You also agree to not use (or attempt to use) the Widget or any component of the Widget to display content other than the content provided or intended by us to be displayed via a particular Widget.

NOTICE TO THIRD PARTY SITES:  Any content made available in connection with your site, or otherwise, by our Widgets, third party widgets or otherwise is our exclusive property and no grant of any intellectual property rights is made by us.  We retain the right to demand that you cease any use of our content upon notice.

We Own All Rights In and To Our Service; Accordingly, Your Use of Our Service is Subject to Certain Restrictions and Limitations: Our Service (including, without limitation, all text, photographs, graphics, video and audio content) is protected by copyright as a collective work or compilation under the copyright laws of the United States and other countries. All individual articles, content and other elements comprising our Service are also copyrighted works. You must abide by all additional copyright notices or restrictions contained in our Service.  As between COMPANY and you, COMPANY is the sole owner of all content comprising our Service, including without limitation, all applicable U.S. and non-U.S. copyrights, patents, trademarks, and trade secrets, and other intellectual property rights thereto.  You acknowledge and agree that you will not, directly or indirectly, contest, challenge, aid or abet in contesting or challenging our ownership of such content, or take any action whatsoever in derogation of our rights therein.  You acknowledge and agree that you will not acquire or claim any rights in our Service, or aid or abet anyone else in doing so.

Unless expressly permitted, you may not copy, reproduce, distribute, publish, enter into a database, display, perform, modify, create derivative works, transmit, or in any way exploit any part of our Service, except that you may download material from our Service for your own personal use as follows: you may make one print copy that is limited to occasional articles of personal interest only.  Without limiting the generality of the foregoing, you may not distribute any part of this Service over any network, including, without limitation, a local area network, nor sell or offer it for sale. In addition, these files may not be used to construct any kind of database.
We are concerned about the integrity of our Service when it is viewed in a setting created by a third party that includes advertising or other materials that we have not authorized to be displayed with our Service.  Neither you nor any third party shall make use of the contents of the Service in any manner that constitutes an infringement of our rights, including copyright or that has not been authorized by us.

You acknowledge and agree that content you view, submit or post is at your own discretion and risk, including any reliance on the accuracy, completeness, or usefulness of such content. You acknowledge that you may not rely on any information, data, text, music, sound, photographs, graphics, video, messages or other materials created by or submitted to us, including any content.  You further acknowledge and agree that the views expressed in our Service do not necessarily reflect the views of COMPANY, and COMPANY does not support or endorse content (whether or not edited by COMPANY) posted or submitted by you or any other user.

You Should Review Our Privacy Policy: We are committed to protecting your privacy and security and have explained in detail the steps we take to do so. We urge you to read our privacy policy here.

You Have Rights if You Think Your Copyright is Being Infringed: If you believe that your work has been copied in a way that constitutes copyright infringement, please forward the following information to the contact named below:

— Your username, address, telephone number, and e-mail address;

— A description of the copyrighted work that you claim has been infringed;

— A description of where the alleged infringing material is located;

— A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;

— An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; and

— A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.

Contact —

compscicareers@gmail.com

You Use our Service Subject to Certain Disclaimers: OUR SERVICE IS AVAILABLE “AS IS.”  WE DO NOT WARRANT THAT OUR SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. THERE MAY BE DELAYS, OMISSIONS, INTERRUPTIONS AND INACCURACIES IN THE NEWS, INFORMATION OR OTHER MATERIALS AVAILABLE THROUGH OUR SERVICE.  WE DO NOT MAKE ANY WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THOSE OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO OUR SERVICE OR ANY INFORMATION OR GOODS THAT ARE AVAILABLE OR ADVERTISED OR SOLD THROUGH OUR SERVICE.  WE DO NOT MAKE ANY REPRESENTATIONS, NOR DO WE ENDORSE THE ACCURACY, COMPLETENESS, TIMELINESS OR RELIABILITY OF ANY ADVICE, OPINION, STATEMENT OR OTHER MATERIAL OR DATABASE DISPLAYED, UPLOADED OR DISTRIBUTED IN OUR SERVICE OR AVAILABLE THOUGH LINKS IN OUR SERVICE.  WE RESERVE THE RIGHT (BUT ARE NOT OBLIGATED) TO CORRECT ANY ERRORS OR OMISSIONS IN OUR SERVICE.

ALTHOUGH WE INTEND TO TAKE REASONABLE STEPS TO PREVENT THE INTRODUCTION OF VIRUSES, WORMS, “TROJAN HORSES” OR OTHER DESTRUCTIVE MATERIALS TO OUR SERVICE, WE DO NOT GUARANTEE OR WARRANT THAT OUR SERVICE OR MATERIALS THAT MAY BE DOWNLOADED FROM OUR SERVICE DO NOT CONTAIN SUCH DESTRUCTIVE FEATURES.  WE ARE NOT LIABLE FOR ANY DAMAGES OR HARM ATTRIBUTABLE TO SUCH FEATURES. IF YOU RELY ON OUR SERVICE AND ANY MATERIALS AVAILABLE THROUGH OUR SERVICE, YOU DO SO SOLELY AT YOUR OWN RISK.

OUR SERVICE MAY CONTAIN VARIOUS COMBINATIONS OF TEXT, IMAGES, AUDIOVISUAL PRODUCTIONS, OPINIONS, STATEMENTS, FACTS, ARTICLES, MARKET DATA, STOCK QUOTES OR OTHER INFORMATION CREATED BY
Computerscience.careers  OR BY THIRD-PARTIES.  DUE TO THE NUMBER OF SOURCES FROM WHICH CONTENT IN OUR SERVICE IS OBTAINED, AND THE INHERENT HAZARDS OF ELECTRONIC DISTRIBUTION, THERE MAY BE DELAYS, OMISSIONS OR INACCURACIES IN SUCH CONTENT.  ACCORDINGLY, SUCH CONTENT, INCLUDING THE MARKET DATA, IS FOR YOUR REFERENCE ONLY AND SHOULD NOT BE RELIED UPON BY YOU FOR ANY PURPOSE.  SUCH CONTENT IS NOT INTENDED FOR THE PURPOSE OF TAX OR INVESTMENT ADVICE AND IT DOES NOT ADVOCATE THE PURCHASE OR SALE OF ANY SECURITY OR INVESTMENT. INFORMATION CREATED BY THIRD PARTIES THAT YOU MAY ACCESS ON THE SERVICE OR THROUGH LINKS IS NOT ADOPTED OR ENDORSED BY COMPANY OR SITE AND REMAINS THE RESPONSIBILITY OF SUCH THIRD PARTIES.

We Have No Responsibility for Links to Other Sites or Services: We are not responsible for the availability or content of other services that may be linked to our Service.  Because we have no control over such services, you acknowledge and agree that we are not responsible for the availability of such external services, and that we do not endorse and are not responsible or liable for any content, accuracy, quality, advertising, products or other materials on or available from such services.  You further acknowledge and agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, goods or services available on or through such services.  Any such links do not imply our endorsement of or association with the linked sites.  We reserve the exclusive right, at our sole discretion, to add, change, decline or remove, without notice, linked sites.

YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH OTHERS FOUND THROUGH OUR SERVICE, INCLUDING, WITHOUT LIMITATION, THE PAYMENT AND DELIVERY OF PRODUCTS AND SERVICES, AND ANY TERMS, CONDITIONS, WARRANTIES AND REPRESENTATIONS ASSOCIATED WITH ANY SUCH DEALINGS, ARE SOLELY BETWEEN YOU AND THE THIRD PARTY.

SPECIAL NOTICE: LINKED SITES MAY CONTAIN CONTENT AND GRAPHICS THAT CONTAIN SEXUALLY EXPLICIT MATERIAL UNSUITABLE FOR MINORS, OR THAT MAY OTHERWISE BE OFFENSIVE.  IF YOU ENTER THESE LINKED SITES, YOU ASSERT THAT YOU ARE OF LEGAL ADULT AGE IN YOUR JURISDICTION TO VIEW SUCH MATERIALS AND THAT THE VIEWING, READING, AND/OR DOWNLOADING OF CONTENT FROM THESE LINKED SITES DOES NOT VIOLATE THE COMMUNITY STANDARDS OF YOUR LOCALITY, CITY, TOWN, COUNTY, STATE, PROVINCE, COUNTRY OR OTHER COMMUNITY TO WHICH YOU BELONG, AND/OR FROM WHICH YOU ACCESS THESE LINKED SITES.

Subject to Certain Conditions You May Link to Us on Your Own Site: We grant you the revocable permission to link to our website; provided, however, that your website: (a) must not frame or create a browser or border environment around any of the content on our website or otherwise mirror any part of our website (except as explicitly permitted as described in the “WIDGET” section above); (b) must not imply that we or our Service is endorsing or sponsoring it or its products, unless we have given you prior written consent; (c) must not present false information about, or disparage, tarnish, or otherwise, in our sole opinion, harm COMPANY or its products or services; (d) must not use any COMPANY trademarks without prior written permission from COMPANY; (e) must not contain content that could be construed as distasteful, offensive or controversial or otherwise objectionable (in our sole opinion), and (f) must be owned and controlled by you or the person or entity placing the link, or otherwise permit you to enable such link subject to this User Agreement.  By linking to our website, you agree that you do and will continue to comply with the above linking requirements.

Notwithstanding anything to the contrary contained in this User Agreement, we reserve the right to prohibit linking to our website for any reason in our sole and absolute discretion.

Our Service May Offer Features and Services That Are Available to You Via Your Mobile Device.  These features and services may include, without limitation, the ability to upload content to our Service, receive messages from our Service, download applications to your mobile phone or access features of our Service (collectively, the “Mobile Features”).  We may charge for Mobile Features and these charges will be disclosed prior to completion of registration for the Mobile Feature. Also, standard messaging, data and other fees may be charged by your carrier. Fees and charges will appear on your mobile bill or be deducted from your pre-paid balance. Your carrier may prohibit or restrict certain Mobile Features and certain Mobile Features may be incompatible with your carrier or mobile device. Contact your carrier with questions regarding these issues.  As applicable, instructions regarding how to opt-out of Mobile Features will be disclosed in connection with Mobile Features.  Typically, you will text a keyword (e.g., “STOP”) to the applicable shortcode for the Mobile Feature.

You agree that the Mobile Features for which you are registered may send communications to your mobile device regarding us. Further, we may collect information related to your use of the Mobile Features. If you have registered for Mobile Features, you agree to notify us of any changes to your mobile number and update your account(s) on our Service to reflect this change.

Our Liability to You is Limited: COMPANY and its affiliates, and their respective members, directors, officers, managers, employees, shareholders, agents and licensors are not liable for incidental, indirect, consequential, special, punitive, or exemplary damages of any kind, including, without limitation, lost revenues or profits, loss of business or loss of data, in any way related to our Service or for any claim, loss or injury based on errors, omissions, interruptions or other inaccuracies in our Service.  Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, COMPANY’s liability shall be limited to the extent permitted by law.  Any claim against us shall be limited to the amount you paid, if any, for use of our Service.  We have no special relationship with or fiduciary duty to you.

You agree that in the event you incur any damages, losses or injuries that arise out of our acts or omissions, the damages, if any, caused to you are not irreparable or sufficient to entitle you to an injunction preventing any exploitation of our Service, and you will have no rights to enjoin or restrain the development, production, distribution, advertising, exhibition or exploitation of our Service or other materials owned or controlled by us.

By accessing our Service, you understand that you may be waiving rights with respect to claims that are at this time unknown or unsuspected, and in accordance with such waiver, you acknowledge that you have read and understand, and hereby expressly waive, the benefits of Section 1542 of the Civil Code of California, and any similar law of any state or territory, which provides as follows: “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.”

You Agree to Indemnify Us Based on Your Use of the Service: You agree to indemnify and hold harmless COMPANY and its affiliates, and their respective members, directors, officers, managers, employees, shareholders, agents, and licensors, from and against all losses, expenses, damages and costs, including reasonable attorneys’ fees, resulting from or relating to any use or misuse by you of our Service, including without limitation our email publications and/or website, or any violation by you of this User Agreement or any breach by you of your representations and warranties hereunder.  We reserve the right to take over the exclusive defense of any claim for which we are entitled to indemnification under this Section. In such event, you shall provide us with such cooperation as is reasonably requested by us.

The Provisions of this User Agreement are Severable; This User Agreement Constitutes Our Entire Agreement: If any part of this User Agreement is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.  This User Agreement, together with our Privacy Policy, constitutes the entire agreement between you and us with respect to our Service, including use of our email publications and/or website, and supersedes all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and us with respect to our Service.  Any failure by us to exercise any right provided for herein shall not be deemed a waiver of any further rights hereunder.

You May Not Assign This User Agreement: You shall not transfer, assign, sublicense nor pledge in any manner whatsoever, any of your rights or obligations under this User Agreement. COMPANY may transfer, assign, sublicense or pledge in any manner whatsoever, any of its rights and obligations under this User Agreement to a subsidiary, affiliate, or successor thereof or to any third party whatsoever, without notifying you or receiving your consent.

Certain Territorial Restrictions May Apply to Your Use of Our Service:  Our Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country.  We control our Service from offices located in the United States and makes no representations or warranties that the information, products or services contained in our Service are appropriate for use or access in other locations. Anyone using or accessing our Service from other locations does so on their own initiative and are responsible for compliance with United States’ and local laws regarding online conduct and acceptable content, if and to the extent such local laws are applicable. We reserve the right to limit the availability of our Service to any person, geographic area, or jurisdiction, at any time and in our sole discretion.

Any Dispute Between Us Will Be Governed by Washington State Law:  This User Agreement shall be governed by the laws of the United States and the State of Washington applicable to agreements made and to be performed therein without regard to conflict of laws principles.  You expressly agree that exclusive jurisdiction for any claim or dispute with COMPANY or relating in any way to your use of our Service resides in the courts of the United States located in the Southern District of Washington or any state court located in Clark County, Washington AND WAIVE ANY RIGHT TO RESORT TO ANY FORM OF CLASS ACTION.  Any cause of action or claim you may have with respect to our Service must be commenced within one (1) year after such claim or cause of action arises.

The caption to each paragraph of this User Agreement is for the convenience of reference only and shall be ignored in the construction or interpretation hereof.

</p>
        </div>
      </div>
   
  )
}
